services:
  postgres_project1:
    image: postgis/postgis:15-3.3
    container_name: redpatitas_postgres_project1
    environment:
      POSTGRES_DB: redpatitas_db
      POSTGRES_USER: redpatitas
      POSTGRES_PASSWORD: redpatitas_pass
    ports:
      - "5433:5432"
    volumes:
      - db_project1_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration/V1__init_schema.sql:/docker-entrypoint-initdb.d/01_init.sql
    networks:
      - redpatitas_net

  nginx_static:
    image: nginx:stable-alpine
    container_name: redpatitas_static
    ports:
      - "8081:80"
    volumes:
      - ./local-uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - postgres_project1
    networks:
      - redpatitas_net

  auth-db:
    image: postgres:17-alpine
    container_name: redpatitas_auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: redpatitas
      POSTGRES_PASSWORD: redpatitas
    volumes:
      - auth_redpatitas_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - redpatitas_net

  auth-backend:
    build: ../authentication
    ports:
      - "8082:8082"
    depends_on:
      auth-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - redpatitas_net

volumes:
  db_project1_data:
  auth_redpatitas_data:

networks:
  redpatitas_net:
    driver: bridge